
services:
  frontend:
    # Nombre del contenedor para fácil referencia
    container_name: pokeapi_frontend
    # Indica dónde está el Dockerfile para construir la imagen
    build:
      context: .
      dockerfile: app/Dockerfile
    # Monta el código local (el subdirectorio 'app') en el directorio de trabajo del contenedor
    volumes:
      - ./app:/app
    # Mapea el puerto 5173 del contenedor al puerto 5173 de tu máquina
    ports:
      - "5173:5173"
    # Mantener el contenedor en ejecución para que podamos usar 'make shell' o 'make dev'
    tty: true
    stdin_open: true
    # Comando para iniciar el servidor de desarrollo
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend

  backend:
    # Nombre del contenedor para fácil referencia
    container_name: pokeapi_backend
    # Indica dónde está el Dockerfile del backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    # Monta el código del backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    # Mapea el puerto 3000 del contenedor
    ports:
      - "3000:3000"
    # Variables de entorno desde .env
    env_file:
      - .env
    # Mantener el contenedor en ejecución
    tty: true
    stdin_open: true
    # Comando para iniciar el servidor backend
    command: sh -c "npm install && npm run dev"